import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/menu/app-sidebar"
import { TooltipProvider } from "@/components/ui/tooltip"

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.variable)}
    >
      <body className="h-full">
        <SidebarProvider>
          <div className="flex h-full w-full">
            <AppSidebar />

            <main className="flex-1 min-w-0 h-full">
              <SidebarTrigger />
              <TooltipProvider>
                {children}
              </TooltipProvider>
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
